=== DDog1/College-work-from-2013-2017/2016-2017/Web Services/Lab1/skiHolidaySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/skiHolidaySchema" xmlns:tns="http://www.example.org/skiHolidaySchema" elementFormDefault="qualified">
	<xs:element name="skiHoliday">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="person" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							
							<xs:element name="personal">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string"/>
										<xs:element name="address" type="xs:string"/>
										<xs:element name="DOB" type="xs:string"/>
										<xs:element name="sex" type="xs:string"/>
										<xs:element name="phone" type="xs:string"/>
										<xs:element name="NOK" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							
							<xs:element name="holiday">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="type" type="xs:string"/>
										<xs:element name="date" type="xs:date"/>
										<xs:element name="duration" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DDog1/College-work-from-2013-2017/2016-2017/Web Services/Lab1/skiHoliday.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:skiHoliday xmlns:p="http://www.example.org/skiHolidaySchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/skiHolidaySchema skiHolidaySchema.xsd ">
	<p:person>
		<p:personal>
			<p:name>Darren Cosgrave</p:name>
			<p:address>Dublin</p:address>
			<p:DOB>10/10/1994</p:DOB>
			<p:sex>Male</p:sex>
			<p:phone>0123456789</p:phone>
			<p:NOK>Mother</p:NOK>
		</p:personal>
		<p:holiday>
			<p:type>Winter Skiing</p:type>
			<p:date>2017-01-24</p:date>
			<p:duration>2 Weeks</p:duration>
		</p:holiday>
	</p:person>
	
	<p:person>
		<p:personal>
			<p:name>Ryan Cosgrave</p:name>
			<p:address>Dublin</p:address>
			<p:DOB>01/01/2000</p:DOB>
			<p:sex>Male</p:sex>
			<p:phone>0123456789</p:phone>
			<p:NOK>Father</p:NOK>
		</p:personal>
		<p:holiday>
			<p:type>Winter Skiing</p:type>
			<p:date>2017-01-24</p:date>
			<p:duration>2 Weeks</p:duration>
		</p:holiday>
	</p:person>
</p:skiHoliday>
